const emojis = [
    { id: 1,pic: "😀", name: "Grinning Face" },
    { id: 2,pic: "😂", name: "Face with Tears of Joy" },
    { id: 3,pic: "😍", name: "Smiling Face with Heart-Eyes" },
    { id: 4,pic: "😎", name: "Smiling Face with Sunglasses" },
    { id: 5,pic: "😢", name: "Crying Face" },
    { id: 6,pic: "😡", name: "Angry Face" },
    { id: 7,pic: "🥳", name: "Partying Face" },
    { id: 8,pic: "😱", name: "Face Screaming in Fear" },
    { id: 9,pic: "🤔", name: "Thinking Face" },
    { id: 10,pic: "🙃", name: "Upside-Down Face" },
    { id: 11,pic: "🤩", name: "Star-Struck" },
    { id: 12,pic: "😴", name: "Sleeping Face" },
    { id: 13,pic: "😬", name: "Grimacing Face" },
    { id: 14,pic: "🤗", name: "Hugging Face" },
    { id: 15,pic: "😇", name: "Smiling Face with Halo" },
    { id: 16,pic: "🤑", name: "Money-Mouth Face" },
    { id: 17,pic: "😈", name: "Smiling Face with Horns" },
    { id: 18,pic: "💀", name: "Skull" },
    { id: 19,pic: "👻", name: "Ghost" },
    { id: 20,pic: "🎃", name: "Jack-O-Lantern" },
    { id: 21,pic: "🎉", name: "Party Popper" },
    { id: 22,pic: "🔥", name: "Fire" },
    { id: 23,pic: "🌈", name: "Rainbow" },
    { id: 24,pic: "⭐", name: "Star" },
    { id: 25,pic: "💖", name: "Sparkling Heart" },
    { id: 26,pic: "🍕", name: "Pizza" },
    { id: 27,pic: "🎈", name: "Balloon" },
    { id: 28,pic: "🐶", name: "Dog Face" },
    { id: 29,pic: "🐱", name: "Cat Face" },
    { id: 30,pic: "🦄", name: "Unicorn Face" }
];
module.exports = {
    emojis,
};

